# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

spack:
  # add package specs to the `specs` list
  specs:
  - icon@develop%nvhpc +ecrad +rte-rrtmgp +mixed-precision serialization=create ~coupling +dace fcgroup=DACE.externals/dace_icon.-O1 +grib2
  - eccodes@2.19.0%nvhpc
  - nvidia-blas%nvhpc
  - nvidia-lapack%nvhpc
  - libxml2@2.9.13%gcc
  - serialbox@2.6.1%nvhpc
  - boost@1.82.0%gcc
  view: false
  concretizer:
    unify: true
  develop:
    icon:
      spec: icon@develop%nvhpc +ecrad +rte-rrtmgp +mixed-precision serialization=create ~coupling +dace fcgroup=DACE.externals/dace_icon.-O1 +grib2
      path: ../../../../../

