# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

spack:
  specs:
  - icon@develop%cce@12.0.3 +ecrad +rte-rrtmgp serialization=create +dace fcgroup=DACE.externals/dace_icon.-O1 +grib2 ~coupling
  - eccodes@2.19.0%cce
  - cray-libsci@20.06.1%cce
  - libxml2@2.9.13%gcc
  - boost@1.82.0%gcc
  - serialbox@2.6.1%cce
  - cmake%gcc@9.3.0
  view: false
  concretizer:
    unify: true
  develop:
    icon:
      spec: icon@develop%cce@12.0.3 +ecrad +rte-rrtmgp serialization=create +dace fcgroup=DACE.externals/dace_icon.-O1 +grib2 ~coupling
      path: ../../../../../
